### ISSUE TITLE
ContributionsWrite - does not update placeholder data for "Content" after language selection

### ISSUE THREAD

**Issue by Hrabovszki1023** [Human-Connection/WebApp#138]
See Placeholder "Write something amazing ..." in Content-field

The language was selected from "english" to "german"

![image](https://user-images.githubusercontent.com/15831418/40077598-6e3059ca-5882-11e8-8541-7b6b65fe7182.png)

**Comment by roschaefer** [comment]
For the record: @appinteractive and I covered this issue in our online meeting.

[See these lines](https://github.com/Human-Connection/WebApp/blob/develop/components/Contributions/ContributionsForm.vue#L353) for the implementation of the translated placeholder.

Quill editor is not part of the usual update mechanism of VueJS. One easy way to fix this is to leave the placeholder blank.
