### ISSUE TITLE
Contributions without categories are hidden in newsfeed

### ISSUE THREAD

**Issue by visualjerk** [Human-Connection/WebApp#19]

**Comment by appinteractive** [comment]
You mean they should be hidden right? Without category they are private.

**Comment by visualjerk** [comment]
So this behaviour is correct? I assumed they should be visible when no category filters are set.

Privacy should be handled through a separate attribute.

**Comment by sebako86** [comment]
yea it should be a separate attribute otherwise I can't use categories to order my private stuff and that's what users should be able to right?

**Comment by appinteractive** [comment]
We have a visibility Attribute for that reason. But a contribution can’t be public without at least one category. We have to warn the user when saving a contribution while public and no contributions selected.

Gruß Greg.

-

Grzegorz Leoniec { Software Engineer }

Mail: greg@app-interactive.de • Tel: +49 (0)179-9215177

Am 24. Feb. 2018, 12:45 +0100 schrieb Sebo <notifications@github.com>:

**Comment by visualjerk** [comment]
That seems like a good solution. Pherhaps we could even make at least one category required in combination with visibility public.

**Comment by appinteractive** [comment]
Now at least one category is required
