### ISSUE TITLE
Multiple Notification bug

### ISSUE THREAD

**Issue by Mastercuber** [Human-Connection/WebApp#199]
**Describe the bug**
The Bug is somewhere in the notification system. I got 5 times the same notification when someone issued me in another comment!
What also happend was the following: I upvoted two comments of a post. And I got 2 notifications.. I dont know if this is the expected behaviour.

**To Reproduce**
1. Go to a post
2. Write a comment and issue someone it it
3. See how much notifications the issued person got

**Expected behavior**
I expected to get 1 notification instead of 5 times the same one. Maybe I misunderstood something..

**Screenshots**
Will be comming soon. I'm not be able to access the webserver. Gateway timeout..
But for now: Just look at the notifications.

**Desktop (please complete the following information):**
 - OS: Debian based linux
 - Browser: Firefox Quantum
 - Version: 61.0.1

**Comment by appinteractive** [comment]
Thanks for your bug report. I found the issue and opened a pull request that should fix the issue.

**Comment by appinteractive** [comment]
@Mastercuber did that happen to you in the last month?

**Comment by Mastercuber** [comment]
No, can't see this behaviour in the last time

**Comment by appinteractive** [comment]
Was fixed with a other issue by @visualjerk
