### ISSUE TITLE
Standardise grammar of German pronouns "du", "dein", etc.

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/WebApp#239]
**Describe the bug**
In the German version of the WebApp and some transactional emails the pronouns are written inconsistently: "du/Du, dein/Dein, deine/Deine, deinem/Deinem, deiner/Deiner, deins/Deins, dich/Dich, dir/Dir".
Example:

> Hier kannst Du Deine Daten herunterladen indem du einen Download-Link anforderst, der an deine E-Mail-Adresse geschickt wird.

**Expected behavior**
Consistant grammar for all German texts of a) the WebApp and b) of transactional emails.

Duden recommends **lowercase**, except at the beginning of a sentence and as an option for letters, see https://www.duden.de/rechtschreibung/dein_Possessivpronomen.

A style guide for developers/editors might be helpful for future texts.

**Comment by appinteractive** [comment]
Good point, I never got that big versions. I mean I would not feel insulted by a lower case version of “du” 😬

**Comment by roschaefer** [comment]
Quoting Hardy (core-team member):
```
Wir (das HC-Team) haben uns irgendwann darauf geeinigt, dass wir Anreden wie Du, Ihr, Euch etc. immer mit großem Anfangsbuchstaben schreiben. Konntest Du natürlich noch nicht wissen … aber ab jetzt gibt's keine Ausreden mehr ;-)
```

**Comment by roschaefer** [comment]
@christianeiselt could you fix that on the login page? (next easy contribution, yay! :wink: )

**Comment by appinteractive** [comment]
I do not like the big version as this is not a letter! Just my opinion, we get complains from the community that we are to “marketing oriented” and this is one of those things that are “over engendered” in my opinion.

**Comment by Lulalaby** [comment]
@appinteractive reference inserted See https://github.com/Human-Connection/WebApp/commit/baf41153f53d266dfc3cc87095f81b947829b7c7

**Comment by christianeiselt** [comment]
@appinteractive I just signed up at lokalise.co and saw that some text are quite different to the de.json... i.e.: Lokalise: `Beachte dass Deine Kommentare, Beiträge, Can Do, etc. wichtig für unseren Austausch in der Gemeinschaft sind. Falls Du diese dennoch löschen möchtest, musst Du dies unten markieren und zusätzlich bestätigen.` vs de.json: `Beachte das Deine Kommentare, Beiträge, CanDo’s, etc. wichtig für unsere Community sind. Falls Du diese mit Deinem Benutzerkonto löschen möchtest, musst Du unten die entsprechenden Haken setzen.`.  Can't we link the text somehow? With a single source? I'm afraid this will become really messy...

**Comment by Lulalaby** [comment]
@christianeiselt #286
