### ISSUE TITLE
[Bug] Number of comments being displayed is restricted to 100

### ISSUE THREAD

**Issue by ionphractal** [Human-Connection/WebApp#248]
**Describe the bug**
Articles do not display more than 100 comments. However, new comments are accepted without error. There is also no pagination to scroll through.

**To Reproduce**
1. Create an article
2. Create more 100 comments then try to create more

**Expected behavior**
For performance, comments should be paginated where I would prefer to see the last comment page  that I visited, or any other means to see which comments are unread.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser Firefox
 - Version 61.0.2

**Comment by appinteractive** [comment]
The question would be, how should it behave when there are 300 comments and only 2 new ones when you reach the page again?

**Comment by ionphractal** [comment]
@appinteractive In case pagination size is 100 and you're talking about the 301st and 302nd comment, that's obviously page 4, otherwise (298th and 299th) page 3.

Hm... ok maybe it's too sophisticated for now. What matters most to me is that there's some sort of pagination anyhow.

Actually it just flashed my mind that one could also do it like this: display the "newest N(e.g. 100)" by default with some "load older comments" button between the article and the comment section.

**Comment by appinteractive** [comment]
Pagination only works when sorting the comments from newest to oldest, but the other way around (our case) it does not fit logically in my opinion. 

Do you have a working example on other pages that you would consider ideal?

**Comment by appinteractive** [comment]
You are right. Seems my brain is currently in recovery mode 😅 the 100 pagination was just a quick fix. 

Would you @ionphractal want to try implementing a „load more“ button?

**Comment by ionphractal** [comment]
Alright, will give it a shot. Gotta get setup and read into the code so will probably become mid/end of coming week.

**Comment by mimicc83** [comment]
@ionphractal feel free to join us on discord if you havn't already https://discord.gg/ZKzxKKR

**Comment by ionphractal** [comment]
Got it done, for now it's a "load all" button as I'm a lazy person and don't want to click so much. I wonder if it was better to drop the default $limit to maybe 10 or so now to improve page loading speed when you're not much interested in the comments... what do you think?
