### ISSUE TITLE
Disabling links to profiles in editor

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/WebApp#254]
**Describe the bug**
While editing on a mobile device one can easily accidently touch an link to an @profile. When doing so, the profile is loaded and all the written text is gone forever. While writing a text there is no need for a touchable link to a profile.

**To Reproduce**
1. Edit a new article
2. reference a @profile in that text
3. touch it
4. The profile loads and the text is gone

**Expected behavior**
The profile should not be a working link while editing text

**Screenshots**

**Desktop (please complete the following information):**
 - OS: all mobile

**Smartphone (please complete the following information):**
 - Device: all touchscreen devices

**Comment by sebako86** [comment]
The link for the profile should stay - however we need a warning alert that leaving the page will result in the loss of all contents. 

@roschaefer this should be a good issue for the new guys on board to learn how events work in vuejs.

**Comment by sebako86** [comment]
@roschaefer yes we can close that one but take in my recent comment and keep links active but implement a warning when a user is about to leave a page containing unsaved content. Thanks!
