### ISSUE TITLE
Centralize ReadMe-content to docs.human-connection.org

### ISSUE THREAD

**Issue by christianeiselt** [Human-Connection/WebApp#257]
Currently the need for the components yarn, NodeJS are not described in the ReadMe.md of the WebApp.
I suggest to centralize the documention to [docs](https://docs.human-connection.org/server-api/installation.html) and link to the corresponding articles from within the ReadMe.md (same in API). Then there is no redundancy in content and still a starting point in every repository.

**Comment by Lulalaby** [comment]
Is this already in work, or shall i do it? @mimicc83 @christianeiselt

**Comment by appinteractive** [comment]
@christianeiselt are you on it?

Die docs need some love indeed! There is quite some work.

**Comment by christianeiselt** [comment]
@Lulalaby @appinteractive  I wanted to start with this one, but I learned that there is a whole docs repository. I'd suggest to keep only links in the ReadMe.md (in API as well as in WebApp etc.), and put the whole setup information in the docs. That way we only have to maintain one source...

**Comment by appinteractive** [comment]
I think we need a good workflow to get people to contribute to the docs. Or at least a workflow or roadmap for our selves.

**Comment by Lulalaby** [comment]
> 
> 
> I think we need a good workflow to get people to contribute to the docs. Or at least a workflow or roadmap for our selves.

your right @appinteractive 
Let's do this

**Comment by christianeiselt** [comment]
Yeah, that sounds about right... I'll stay put on this one for the moment...

**Comment by Lulalaby** [comment]
Thanks @christianeiselt

**Comment by roschaefer** [comment]
I didn't know about https://docs.human-connection.org/. I would prefer to keep the individual READMEs short and just link to.

Where does the code for the gitbook come from?

**Comment by Lulalaby** [comment]
@roschaefer https://github.com/Human-Connection/Documentation

**Comment by roschaefer** [comment]
Nice
