### ISSUE TITLE
Query for invitation code by email

### ISSUE THREAD

**Issue by datenbrei** [Human-Connection/WebApp#264]
**Is your feature request related to a problem? Please describe.**
Some of our new users have troubles on first sign in. We believe there is a mismatch of the generated invitation codes sent to the user and in our database. As an admin, I would like to double check the invitation code and send a correct code to the user.

**Describe the solution you'd like**
On the admin interface I would like to search for an invitation code entering a given email address. As admin I know the user's email address already.

**Describe alternatives you've considered**
For security, there should be no endpoint in the API that sends a list of all email addresses. An invitation code for a known email address is enough to solve the problem.

**Additional context**
This would be a good place for the query in the Admin UI:
![screenshot_2018-09-13 kategorien verwalten - human connection](https://user-images.githubusercontent.com/13457963/45491032-f930b200-b768-11e8-99a9-2a214866d4df.png)

**Comment by appinteractive** [comment]
I would stick it to the users screen, but maybe add a modal for the search.

**Comment by appinteractive** [comment]
closed with #264
