### ISSUE TITLE
HC Logo is not a link

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/WebApp#267]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I middle-click on the HC logo on the top left "back to home" and no tab opens.

**Describe the solution you'd like**
The home logo should be a link.

**Describe alternatives you've considered**
Nah, this is a best practice in web development. Make the link a real anchor `<a .. >`.

**Additional context**
![screenshot 5](https://user-images.githubusercontent.com/2110676/45588132-03d97b80-b910-11e8-8f7a-8b693cd7f600.png)

**Comment by brickmaker17** [comment]
Is this still a issue? If so I would like to try and work on it ?

**Comment by roschaefer** [comment]
Yes it is still an issue. You are more than welcome to try and work on it. If you need help or want to know more about the frameworks in use, feel free to join our open source community chat, which is discord at the moment: https://discord.gg/6ub73U3
