### ISSUE TITLE
Organisation tag update failed

### ISSUE THREAD

**Issue by Lulalaby** [Human-Connection/WebApp#274]
**Describe the bug**
Cannot update organisation tags

**Expected behavior**
update with no warning

**Screenshots**
![2018-09-18_23h57_02](https://user-images.githubusercontent.com/14029133/45718972-2f25ca00-bb9f-11e8-94fa-f040f4800195.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox Developer Edition
 - Version 63.0b

**Comment by appinteractive** [comment]
Please wait with fixes until the organization pr is merged

**Comment by Lulalaby** [comment]
aye aye
