### ISSUE TITLE
Locale centralize

### ISSUE THREAD

**Issue by Lulalaby** [Human-Connection/WebApp#286]
> 
> 
> @appinteractive I just signed up at lokalise.co and saw that some text are quite different to the de.json... i.e.: Lokalise: `Beachte dass Deine Kommentare, Beiträge, Can Do, etc. wichtig für unseren Austausch in der Gemeinschaft sind. Falls Du diese dennoch löschen möchtest, musst Du dies unten markieren und zusätzlich bestätigen.` vs de.json: `Beachte das Deine Kommentare, Beiträge, CanDo’s, etc. wichtig für unsere Community sind. Falls Du diese mit Deinem Benutzerkonto löschen möchtest, musst Du unten die entsprechenden Haken setzen.`. Can't we link the text somehow? With a single source? I'm afraid this will become really messy...

Quote of christianeiselt
#239 
#285 

**TODO** 
centralize

**Comment by christianeiselt** [comment]
looks like we can automate this: https://blog.lokalise.co/deploying-lokalise-into-your-workflow-best-practices/

**Comment by Lulalaby** [comment]
@appinteractive

**Comment by appinteractive** [comment]
We have to trigger it manually at the moment. 😞 could not get the hook working

**Comment by Lulalaby** [comment]
Woran hängt's? Kann ich vll helfen

**Comment by appinteractive** [comment]
There is a new Pullrequest from lokalize after I imported the current state from develop and setup a webhook which updates the strings inside lokalize. Please take a look at the #299 .

We still need to trigger the import from lokalize manually but thats okay as fare as I'm concerned.

**Comment by christianeiselt** [comment]
@appinteractive Have you seen this article: https://docs.lokalise.co/api-and-cli/lokalise-cli-tool? I'd say, this could be automated as a nightly task...

**Comment by appinteractive** [comment]
Yeah we could add that to Travis when building the develop branch
