### ISSUE TITLE
Remove "Draft" Dialog when saving contribution

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/WebApp#300]
**Describe the bug**

**To Reproduce**
1. Checkout develop (or use staging)
2. Create a contribution
3. Try to save

**Expected behavior**
**No** "Draft" dialog should appear and we should see the saved contribution

**Screenshots**
![kapture 2018-09-24 at 11 42 32](https://user-images.githubusercontent.com/432828/45945937-7f61b980-bfef-11e8-92ac-3400dcc7808b.gif)

**Appeared after mergin #258** 
@ionphractal

**Comment by ionphractal** [comment]
@appinteractive
oops, will fix

**Comment by roschaefer** [comment]
closed via #306

**Comment by appinteractive** [comment]
@roschaefer this was already fixed!?

**Comment by roschaefer** [comment]
@appinteractive well, I just removed the behaviour for contributions and kept it for comments.

**Comment by roschaefer** [comment]
@appinteractive it's a temporary solution. I want to merge `develop` into `master` before we implement more features

**Comment by appinteractive** [comment]
Slay I see the #300 which fixes it was not merged until now.
