### ISSUE TITLE
About me field

### ISSUE THREAD

**Issue by Lulalaby** [Human-Connection/WebApp#313]
### About me

**Describe the solution you'd like**
In all forums, social networks and other sites where there are user profiles, you can enter your own personal description.
This helps other people to quickly find out something about the person.
I'd like a field "about me" at the marked point.
![hc_feature](https://user-images.githubusercontent.com/14029133/46587787-b75a0980-ca91-11e8-96fb-66e9465515e3.png)

**Describe alternatives you've considered**
In the following example I created a "About me" post.
This is a possible alternative, but the posts can get lost quickly.
[HC Alpha](https://alpha.human-connection.org/contributions/info-uber-mich)

**Comment by brickmaker17** [comment]
Is this still a issue? If so I would like to try and work on it ?

**Comment by Lulalaby** [comment]
@brickmaker17 i would love, if u work on it ^^

**Comment by brickmaker17** [comment]
@Lulalaby What something like this. 
<img width="293" alt="screen shot 2018-10-14 at 10 44 24 pm" src="https://user-images.githubusercontent.com/34072446/46930445-dfea8200-d002-11e8-8b39-024871a38f50.png">

**Comment by mimicc83** [comment]
> 
> 
> @Lulalaby What about something like this.
> <img alt="screen shot 2018-10-14 at 10 44 24 pm" width="293" src="https://user-images.githubusercontent.com/34072446/46930445-dfea8200-d002-11e8-8b39-024871a38f50.png">

try without the text maybe? just the + icon should be sufficient - I'd suggest the non-boxed version of the plus icon

**Comment by Lulalaby** [comment]
yeah

**Comment by Lulalaby** [comment]
While your on it, i saw, that many people writes their city in the nickname.
Maybe adding a field for this to?

**Comment by brickmaker17** [comment]
> While your on it, i saw, that many people writes their city in the nickname.
> Maybe adding a field for this to?

This is what I have so far. Let me know what you think?
<a href="https://imgflip.com/gif/2kafjd"><img src="https://i.imgflip.com/2kafjd.gif" title="made at imgflip.com"/></a>

**Comment by mimicc83** [comment]
@brickmaker17 @Lulalaby 

that's looking good! Thanks! 

these fields would be useful:

- About me
- City/Region
- Age
- .... 

have been thinking about links to other social profiles users can enter but maybe we should wait with that one until it's public. Any other fields you feel necessary on the profiles?

Also a suggestion to not use rounded icons as we usually have squared ones or rounded corners ;-)

Cheers,
Sebo

**Comment by Lulalaby** [comment]
Discord Tag maybe
And GitHub Name

But only shown when exsist

**Comment by mimicc83** [comment]
all fields should be optional yes

**Comment by Lulalaby** [comment]
@brickmaker17 status?

**Comment by barrettluke** [comment]
> @brickmaker17 status?

@Lulalaby Still working on it. Trying to figure out best way add the fields. Maybe a modal opens and the user can fill out a form of all the info to be shown and just have the About me be the only one that toggles a input box?

**Comment by Gerald1614** [comment]
Hi @brickmaker17 , let me know if you think pairing would help on this one.  I would love to help so we could submit a pull request on this one. I would be happy to help if you think that would be usefull. Gerald
