### ISSUE TITLE
Duplicate comments displayed

### ISSUE THREAD

**Issue by roschaefer** [Human-Connection/WebApp#321]
**Describe the bug**
When I submit a comment or when the list of comments is loaded, several duplicate comments are added with an animation. Reloading the page shows the correct number of comments without duplicates.

**To Reproduce**
1. Visit https://staging.human-connection.org/
2. Click on the first contribution
3. Scroll down to "Add comment"
4. Write a comment and click submit

**Expected behavior**
The comment should be added with an animation, but once! Instead it's popping up several times.

**Screenshots**

**Desktop (please complete the following information):**
```sh
robert@e480 ~> chromium --version
Chromium 69.0.3497.100 Arch Linux
```

**Additional context**
This error seems to be "flaky", ie. it does not come up all the time. Reloading the page removes the duplicate comments deterministically.

**Comment by 360fun** [comment]
I noticed this behaviour as well!

**Comment by roschaefer** [comment]
We'll see if this bug is actually closed...

**Comment by Lulalaby** [comment]
I think, let's try
