### ISSUE TITLE
Post Loading

### ISSUE THREAD

**Issue by Lulalaby** [Human-Connection/WebApp#334]
It seem's, that in the profiles only 10 Posts are loaded.
On the main page ~12/14.
Sometimes the main page show's only one row.

This must be a bug or a configuration error in the last fix.

**Comment by Lulalaby** [comment]
![grafik](https://user-images.githubusercontent.com/14029133/47353759-50f1ff80-d6bd-11e8-8ae8-51118c8ae49e.png)

**Comment by Lulalaby** [comment]
> It seem's, that in the profiles only 10 Posts are loaded.

Seem's ok said @roschaefer

**Comment by AndreasAusKiel** [comment]
I found another, very strange, bug:
When I load the alpha in chromium and Ff esr, I get the Post-Snake in one row on the main screen after a browser-page-reload (strg/ctrl-r) in both browsers.
The functionality of the alpha is reduced in both browsers: I can't open the poup-menus for comments (bell) or user (user-icon).
After closing chromium, Ff works fine in all directions again: it shows three columns and creates the popup-menus for comments and user.

Edit: My used system
Distribution        : Debian GNU/Linux unstable (sid)
C-Library        : GNU C Library / (Debian GLIBC 2.27-6) 2.27
Version        : #1 SMP siduction 4.18-19 (2018-10-19)
Kernel        : Linux 4.18.15-towo.2-siduction-amd64 (x86_64)
OpenGL-Renderer        : AMD KABINI (DRM 2.50.0, 4.18.15-towo.2-siduction-amd64, LLVM 6.0.1)
Maschinen-Typ        : Desktop
Hauptspeicher        : 3458MB (2180MB used)
Prozessor        : AMD Sempron(tm) 3850 APU with Radeon(tm) R3

Firefox Quantum 60.2.2esr (64 Bit)
Chromium Version 70.0.3538.67 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)

**Comment by AndreasAusKiel** [comment]
Today, my Firefox Quantum 60.2.2esr (64 Bit) behaves that strange way chromium did before.
BUT:  There is only one tab open with HC-alpha AND no other browser is loaded.
I can't open the above discribed popup-menus and I always see this one-row-post-snake. :-(

Aft4er some klicking between post-view and main-page via HC-icon, I see the threee-row post-page, but no popups. :-(

This way, no logout is possible.

I entered https://alpha.human-connection.org/auth/login into the browser-adress-line.
After logging in again, the side seems to work correctly.
BUT: After a browser-pagereload, I can go to the top of this commend..., The sanke bites itlelf - autsch! :-(

**Comment by Lulalaby** [comment]
FYI Use https://alpha.human-connection.org/auth/logout for logout
