### ISSUE TITLE
[BUG] The view of a post does not jump to the "Comments"section if "Comments" is selected in the right menu.

### ISSUE THREAD

**Issue by Hrabovszki1023** [Human-Connection/WebApp#34]
**Precondition:**
The post is created + saved and a comment exists.

The view of a post will not be moved to the visible area if you select right in the menu "Post"->"Comments".

**Expected:**
It is expected that the view will be moved to the comments

Enviroment: Chrome (Version 64.0.3282.186) on MacOS 10.12.6

**Comment by appinteractive** [comment]
Fixed
