### ISSUE TITLE
@Username: Unique user identification if identical profile names exist

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/WebApp#342]
**Is your feature request related to a problem? Please describe.**
If two or more identical profile names exist it can be hard to select the correct user when addressing a user in a post or comment.

**Describe the solution you'd like**
Profile names should be unique. Allow only unique user names on account creation or profile name change.

**Describe alternatives you've considered**
Provide an additional/another identification method to select the correct user.

**Comment by appinteractive** [comment]
Yeah I was also thinking about showing the slug  too on the mention menu and beside a user. Would be like the equivalent of the twitter handle. 

Did you mean something like this?

**Comment by sushidave** [comment]
Thank you very much for your feedback.
 
In my view we need to show something that's unique, e.g.:
- the username
- the profile image
- the slug
- the location (optional data)

**Assessment:**

Username:
The problem is that the system allows for duplicates. We would have to stop allowing them or use one of the other options.

Profile image:
Although the probability that two or more users have the same username AND profile image (background colour / avatar / picture) it can't be excluded that duplicates will exist.

Slug:
This would be a unique and reliable identifier. However, it's not shown elsewhere on the user interface except in URLs and thus it's little known for the users.

Location:
It's planned that users can optionally store their location in their profile settings. We could use this information on the mention menu but it can't be excluded that more then one user have the same username and location (thinking of large cities or if the user just stores his/her country or region).

**Proposition:**

a) Add the optional location information on the mention menu. This would be user friendly and open opportunities for networking. It minimises the chance of duplicate records appearing on the menu though they can't be avoided.

b) Allow unique user names only. This would be the most practical solution. The effort to have users with identical usernames change them is still low at this early stage.

c) A combination of the two. It would solve the problem with duplicates and help users to better connect with each other locally.

What do you think?

**Comment by Lulalaby** [comment]
I would say, the username shouldn't be unique but the slug then.

The profil picture doesn't need to be unique.

Location unique.. i don't think this is a good idea.

**Comment by sushidave** [comment]
See https://github.com/Human-Connection/Human-Connection/issues/1069
