### ISSUE TITLE
Help pages for the user interface

### ISSUE THREAD

**Issue by sushidave** [Human-Connection/WebApp#359]
**Is your feature request related to a problem? Please describe.**
There are no help pages for the HC UI.

**Describe the solution you'd like**
Publish help pages and add a link on every page (e.g. in the page footer)

**Comment by roschaefer** [comment]
Yep! I like that. Could be more specific, what would you expect on a "Help" or "Quickstart" page?

**Comment by sushidave** [comment]
On help/quickstart pages I'd expect information for newcomers as well as existing users on the handling of the user interface, e.g. 

- how to create a contribution
- how to use @username handles
- how notifications work
- how to edit your profile
- how to become a fan of someone
- how to invite other users
- how to report a bug
- how to request a feature
- how to contact support 
- etc.

Information on things which are not working should be added, like bugs or current features. 

For examples see #faq on the alpha version.

**Comment by sushidave** [comment]
Schedule it as a feature for the beta phase?

**Comment by sushidave** [comment]
See https://github.com/Human-Connection/Human-Connection/issues/1067
