### ISSUE TITLE
Follow Function

### ISSUE THREAD

**Issue by Lulalaby** [Human-Connection/WebApp#382]
Follow function is missing by a user at the alpha

![grafik](https://user-images.githubusercontent.com/14029133/54033794-8a7f5f00-41b5-11e9-853a-67e15af40923.png)

**Comment by appinteractive** [comment]
@Lulalaby please get more information, otherwise we can't do anything here.

**Comment by Lulalaby** [comment]
I don't have more informations.
Please talk with Nick

**Comment by appinteractive** [comment]
I pinged him

**Comment by Nick-HC** [comment]
Its done lads n gents. Talked to the user and getting feedback that he can now follow everyone. :O

**Comment by Lulalaby** [comment]
Nice 
Close #382
