### ISSUE TITLE
Newsfeed keep-alive

### ISSUE THREAD

**Issue by visualjerk** [Human-Connection/WebApp#43]
Currently the newsfeed needs to be rendered every time the user navigates to it. For improved performance we want to add Vue's **keep-alive** in order to keep the rendered state of the newsfeed until the user refreshes the browser window.

This function needs to be added to the nuxt view component, so we have to take care that other pages are not negatively affected by this change.

**Comment by visualjerk** [comment]
Implemented with #44

**Comment by appinteractive** [comment]
It’s Performant on desktops but not on mobile. Looks like it’s loading the whole newsfeed on every back action on iOS.

**Comment by sebako86** [comment]
iOS browser back button works a bit different: https://stackoverflow.com/questions/8788802/prevent-safari-loading-from-cache-when-back-button-is-clicked

**Comment by visualjerk** [comment]
Right now I do not experience any performance issues on iOS using Mobile Safari. Neither in my local nor in the alpha environment. Navigating back to the newsfeed takes roughly one second.

Do you have any custom settings in iOS that may cause this behaviour?

**Comment by appinteractive** [comment]
The issue pops up when you swipe back, but not with the back button. Both behave completly different for some reason.

**Comment by appinteractive** [comment]
![kapture 2018-03-20 at 22 25 27](https://user-images.githubusercontent.com/432828/37683670-a488596c-2c8d-11e8-820a-2f719e2fcc53.gif)

**Comment by appinteractive** [comment]
It also seems like the destroy for non keep alive components does not work properly as you get an the last post in the contribution creation screen instead of empty data. Kind of wearied.

**Comment by appinteractive** [comment]
Seams to be fixed after changing from div with onClock event to a Tag with the event.  Seams like safari on iOS needs that.
