### ISSUE TITLE
Improve Login and Registration

### ISSUE THREAD

**Issue by HC-Team** [Human-Connection/WebApp#5]
- use better validation responses
- step process with indicator

**Comment by HC-Team** [comment]
I think we should rewrite the registration process into a more streamlined multiple step process.

**Comment by ShalokShalom** [comment]
https://github.com/Human-Connection/WebApp/issues/12#issuecomment-373129475

Consider also a decentralized solution.

**Comment by appinteractive** [comment]
Login with 3rd party services will be a topic for the future. If anyone has concrete wishes, just open a ticket for it. The scope of this ticket was not the Auth provider.
