### ISSUE TITLE
✨[Feature Request] Support mp4 Files

### ISSUE THREAD

**Issue by ulfgebhardt** [Human-Connection/WebApp#60]
![image](https://user-images.githubusercontent.com/1238238/38709183-f5ce3e70-3eb9-11e8-96ef-aebabf3eaf7b.png)

mp4 is currently not supported 😢

**Comment by appinteractive** [comment]
It’s an teaser Image field. If you wish to use video, just paste the link to it inside the content.

We will not host memory intensive files at the moment.

**Comment by 001101** [comment]
you mean storage intensive files...?

**Comment by appinteractive** [comment]
Yes indeed I ment storage not memory 😬

**Comment by appinteractive** [comment]
In the future with ipfs we could do that but for now we keep it basic and concentrate on the network logic.
