### ISSUE TITLE
Cover Image issues on Organization Profile

### ISSUE THREAD

**Issue by appinteractive** [Human-Connection/WebApp#69]
We have following issues on the Organization Profile pages:
- if there is no cover image specified, the whole component is missing its the first page or the tab is refreshed
- the cover image is distorted on mobile

**Comment by roschaefer** [comment]
Which component? I tried to reproduce but could not see anything erroneous.

**Comment by appinteractive** [comment]
Seems that that was fixed with the latest organization updates.
